version: "3.7"

services:

  nginx:
    container_name: new_project_nginx
    image: nginx
    volumes:
      - ./projects:/var/www/
      - ./resources/config/nginx/domains:/etc/nginx/conf.d/
    restart: always
    ports:
      - "80:80"
    networks:
      - new-project-network
    depends_on:
      - app

  app:
    container_name: new_project_app
    build:
      context: ./resources
    volumes:
        - ./projects:/var/www/  
        - ./resources/config/startups/config.sh:/opt/config.sh
    command: bash -c "bash /opt/config.sh && tail -f /dev/null"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - new-project-network
    depends_on:
      - mysql

  mysql:
    container_name: new_project_mysql
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ink_dev
    volumes:
      - ./db_mysql:/var/lib/mysql
      - ./resources/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    ports:
    - "3307:3306"
    networks:
      - new-project-network

networks:
  new-project-network:
    driver: bridge

volumes:
  dbdata:
    driver: local